### ISSUE TITLE
Documentation fails to build with Python 3

### ISSUE THREAD

**Issue by Arfrever** [mitsuhiko/click#321]
Documentation fails to build with Python 3.
This problem is still reproducible with Click trunk.
```
$ make html
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.3.1
making output directory...
loading pickled environment... not yet created
loading intersphinx inventory from http://docs.python.org/dev/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 21 source files that are out of date
updating environment: 21 added, 0 changed, 0 removed
reading sources... [  4%] advanced                                                                                                                           
Exception occurred:
  File "/tmp/click/docs/clickdoctools.py", line 73, in isolation
    if isinstance(input, unicode):
NameError: name 'unicode' is not defined
The full traceback has been saved in /tmp/sphinx-err-y2hdbxyj.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
Makefile:40: polecenia dla obiektu 'html' nie powiodły się
make: *** [html] Error 1
$ cat /tmp/sphinx-err-y2hdbxyj.log
# Sphinx version: 1.3.1
# Python version: 3.4.3+ (CPython)
# Docutils version: 0.12 release
# Jinja2 version: 2.7.3
# Last messages:
#   Running Sphinx v1.3.1
#   making output directory...
#   loading pickled environment...
#   not yet created
#   loading intersphinx inventory from http://docs.python.org/dev/objects.inv...
#   building [mo]: targets for 0 po files that are out of date
#   building [html]: targets for 21 source files that are out of date
#   updating environment:
#   21 added, 0 changed, 0 removed
#   reading sources... [  4%] advanced
# Loaded extensions:
#   sphinx.ext.intersphinx (1.3.1) from /usr/lib64/python3.4/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.autodoc (1.3.1) from /usr/lib64/python3.4/site-packages/sphinx/ext/autodoc.py
#   clickdoctools (unknown version) from /tmp/click/docs/clickdoctools.py
#   alabaster (0.7.3) from /usr/lib64/python3.4/site-packages/alabaster/__init__.py
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/usr/lib64/python3.4/site-packages/sphinx/application.py", line 264, in build
    self.builder.build_update()
  File "/usr/lib64/python3.4/site-packages/sphinx/builders/__init__.py", line 245, in build_update
    'out of date' % len(to_build))
  File "/usr/lib64/python3.4/site-packages/sphinx/builders/__init__.py", line 259, in build
    self.doctreedir, self.app))
  File "/usr/lib64/python3.4/site-packages/sphinx/environment.py", line 618, in update
    self._read_serial(docnames, app)
  File "/usr/lib64/python3.4/site-packages/sphinx/environment.py", line 638, in _read_serial
    self.read_doc(docname, app)
  File "/usr/lib64/python3.4/site-packages/sphinx/environment.py", line 791, in read_doc
    pub.publish()
  File "/usr/lib64/python3.4/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/usr/lib64/python3.4/site-packages/sphinx/environment.py", line 126, in read
    self.parse()
  File "/usr/lib64/python3.4/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/usr/lib64/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib64/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib64/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib64/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib64/python3.4/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/usr/lib64/python3.4/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/usr/lib64/python3.4/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/usr/lib64/python3.4/site-packages/sphinx/domains/__init__.py", line 197, in run
    return BaseDirective.run(self)
  File "/tmp/click/docs/clickdoctools.py", line 245, in run
    rv = runner.run('\n'.join(self.content))
  File "/tmp/click/docs/clickdoctools.py", line 186, in run
    'isolated_filesystem': isolated_filesystem,
  File "<docs>", line 1, in <module>
  File "/tmp/click/docs/clickdoctools.py", line 172, in invoke
    with isolation(input=input, env=env) as output:
  File "/usr/lib64/python3.4/contextlib.py", line 59, in __enter__
    return next(self.gen)
  File "/tmp/click/docs/clickdoctools.py", line 73, in isolation
    if isinstance(input, unicode):
NameError: name 'unicode' is not defined
```

**Comment by untitaker** [comment]
Yeah the documentation was never intended to be built with Python 3 (obvious given Armin's IMO destructive attitude towards Python 3)

Pull requests are welcome.

**Comment by mitsuhiko** [comment]
I'm going to close this as WONTFIX for now.  The docs don't even build on windows right now.  When the time comes we can re-open the issue but for now I propose we require one version of Python to build it.
