### ISSUE TITLE
import click fails

### ISSUE THREAD

**Issue by Whitespace** [mitsuhiko/click#326]
Maybe I'm crazy, but click 4.0 is failing on `import`:

```
python                                                                                                                                                             Python 2.7.9 (default, Feb 10 2015, 03:28:08)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.56)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import click
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "click.py", line 8, in <module>
    @click.command()
AttributeError: 'module' object has no attribute 'command'
```

**Comment by davidism** [comment]
Don't name your own module `click`.

**Comment by Whitespace** [comment]
omg I'm an idiot :disappointed:
