### ISSUE TITLE
Crash when PAGER=""

### ISSUE THREAD

**Issue by jonathanslenders** [mitsuhiko/click#403]
In pgcli, click crashes when I set PAGER to be empty.

```python
Traceback (most recent call last):
  File "/home/jonathan/env/pt/bin/pgcli", line 9, in <module>
    load_entry_point('pgcli==0.19.0', 'console_scripts', 'pgcli')()
  ...
  File "/home/jonathan/git/pgcli/pgcli/main.py", line 353, in run_cli
    click.echo_via_pager('\n'.join(output))
  File "/home/jonathan/env/pt/lib/python3.4/site-packages/click-4.1-py3.4.egg/click/termui.py", line 203, in echo_via_pager
    return pager(text + '\n', color)
  File "/home/jonathan/env/pt/lib/python3.4/site-packages/click-4.1-py3.4.egg/click/_termui_impl.py", line 263, in pager
    return _pipepager(text, os.environ['PAGER'], color)
  File "/home/jonathan/env/pt/lib/python3.4/site-packages/click-4.1-py3.4.egg/click/_termui_impl.py", line 292, in _pipepager
    if color is None and cmd_detail[0] == 'less':
IndexError: list index out of range
```

``PipePager`` is called with an empty ``os.environ['PAGER']``: https://github.com/mitsuhiko/click/blob/dbd40696e31409a50eb4722c806b4ac1c527ca8c/click/_termui_impl.py#L263

So, splitting an empty string makes ``cmd_detail`` an empty list. ``[0]`` gives that ``IndexError``:
https://github.com/mitsuhiko/click/blob/dbd40696e31409a50eb4722c806b4ac1c527ca8c/click/_termui_impl.py#L292

**Comment by untitaker** [comment]
Thanks, fixed in master!

**Comment by untitaker** [comment]
Apart from that I'd properly unset PAGER instead of emptying it.

**Comment by jonathanslenders** [comment]
Sure. Thank you!
