### ISSUE TITLE
Passing `file=sys.stdout` breaks click.echo

### ISSUE THREAD

**Issue by mhils** [mitsuhiko/click#425]
We have existing code which passes either `sys.stdout` or a file object to a logging function. I now tried to make this function unicode-aware with click and stumbled upon the following issue:

```python
import click
import sys
click.echo(u'    \x1b[32m\u30d2\x1b[0m', file=sys.stdout)
```
```
λ uname -so
MINGW64_NT-10.0 Msys
λ python --version
Python 2.7.10
λ pip freeze | grep click
click==5.1
λ python utf.py
    Traceback (most recent call last):
  File "utf.py", line 4, in <module>
    click.echo(u'    \x1b[32m\u30d2\x1b[0m', file=sys.stdout)
  File "C:\Users\user\git\venv.mitmproxy\lib\site-packages\click\utils.py", line 314, in echo
    file.write(message)
  File "C:\Users\user\git\venv.mitmproxy\lib\site-packages\click\_compat.py", line 560, in _safe_write
    return _write(s)
  File "C:\Users\user\git\venv.mitmproxy\lib\site-packages\colorama\ansitowin32.py", line 36, in write
    self.__convertor.write(text)
  File "C:\Users\user\git\venv.mitmproxy\lib\site-packages\colorama\ansitowin32.py", line 133, in write
    self.write_and_convert(text)
  File "C:\Users\user\git\venv.mitmproxy\lib\site-packages\colorama\ansitowin32.py", line 158, in write_and_convert
    self.write_plain_text(text, cursor, start)
  File "C:\Users\user\git\venv.mitmproxy\lib\site-packages\colorama\ansitowin32.py", line 166, in write_plain_text
    self.wrapped.write(text[start:end])
  File "C:\Users\user\git\venv.mitmproxy\lib\encodings\cp850.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_map)
UnicodeEncodeError: 'charmap' codec can't encode character u'\u30d2' in position 0: character maps to <undefined>
```
I can reliably reproduce this issue in a normal Windows 10 cmd shell.
As a workaround, one can invoke click with `file=(None if outfile==sys.stdout else outfile)`.

Thanks for making this awesome software! :smiley:

**Comment by mitsuhiko** [comment]
Instead of passing `sys.stdout` you need to pass `click.get_text_stream('stdout')` as sys.stdout does not necessarily support unicode.
