### ISSUE TITLE
click.prompt fails with UnicodeEncodeError on Windows

### ISSUE THREAD

**Issue by ionelmc** [mitsuhiko/click#449]
I get this failure:
```
Traceback (most recent call last):
  File "c:\program files\python 3.5\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python 3.5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python 3.5\Scripts\cookiepatcher.exe\__main__.py", line 9, in <module>
  File "c:\program files\python 3.5\lib\site-packages\click\core.py", line 700, in __call__
    return self.main(*args, **kwargs)
  File "c:\program files\python 3.5\lib\site-packages\click\core.py", line 680, in main
    rv = self.invoke(ctx)
  File "c:\program files\python 3.5\lib\site-packages\click\core.py", line 873, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\program files\python 3.5\lib\site-packages\click\core.py", line 508, in invoke
    return callback(*args, **kwargs)
  File "c:\program files\python 3.5\lib\site-packages\cookiepatcher\cli.py", line 95, in main
    extra_context=extra_context,
  File "c:\program files\python 3.5\lib\site-packages\cookiecutter\main.py", line 129, in cookiecutter
    context['cookiecutter'] = prompt_for_config(context, no_input)
  File "c:\program files\python 3.5\lib\site-packages\cookiecutter\prompt.py", line 129, in prompt_for_config
    val = read_user_variable(key, val)
  File "c:\program files\python 3.5\lib\site-packages\cookiecutter\prompt.py", line 28, in read_user_variable
    return click.prompt(var_name, default=default_value)
  File "c:\program files\python 3.5\lib\site-packages\click\termui.py", line 86, in prompt
    value = prompt_func(prompt)
  File "c:\program files\python 3.5\lib\site-packages\click\termui.py", line 69, in prompt_func
    echo(text, nl=False, err=err)
  File "c:\program files\python 3.5\lib\site-packages\click\utils.py", line 314, in echo
    file.write(message)
  File "c:\program files\python 3.5\lib\encodings\cp437.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_map)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u0103' in position 27: character maps to <undefined>
```

Is unicode text not supported in prompts?

**Comment by mitsuhiko** [comment]
Can you provide a testcase?

**Comment by mitsuhiko** [comment]
Actually, no testcase needed.  You are writing a character to the console that the windows console does not support in the codepage you provided.  Python does not support unicode for the windows console.

**Comment by ionelmc** [comment]
Should at least it show some garbled output? Why does the app need to care about this - isn't click supposed to handle these sort of situations?

**Comment by ionelmc** [comment]
Ok, seems to work if I `chcp 65001` but I still wonder if click could just handle this.

**Comment by mitsuhiko** [comment]
There was some discussion about this.  We could do that but then our stdout behaves differently than the built-in Python one which especially on Python 3 has some bizarre consequences where some surrogate escape based apis will no longer behave as you expect on 3.4 and higher.

It's not entirely sure what to do there.  The absolutely correct thing to do would be to use the unicode APIs for cmd.exe but I cannot see a way to actually do that from within Python because that would require bypassing stdout entirely.

Feel free however to open a feature request separately for making this configurable at the very least or to get more opinions on how to deal with this.

**Comment by mitsuhiko** [comment]
@ionelmc unfortunately cp65001 is ludicrously broken on windows otherwise we would already do this :(
