### ISSUE TITLE
Syntax error on import (message = message or u'')

### ISSUE THREAD

**Issue by niroyb** [mitsuhiko/click#450]
This fails only on Travis python version 3.2 which is (Python 3.2.5)
Here is a link to the [Travis job that made me raise this issue.](https://travis-ci.org/niroyb/Legofy/jobs/89411094)

    Searching for click==5.1
    Best match: click 5.1
    Adding click 5.1 to easy-install.pth file
    Using /home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages
    Searching for Pillow==3.0.0
    Best match: Pillow 3.0.0
    Adding Pillow 3.0.0 to easy-install.pth file
    Using /home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages
    Finished processing dependencies for legofy==0.0.1
    The command "python setup.py install" exited with 0.
    0.12s$ legofy legofy/assets/flower.jpg flower_lego.png
    Traceback (most recent call last):
      File "/home/travis/virtualenv/python3.2.5/bin/legofy", line 9, in <module>
        load_entry_point('legofy==0.0.1', 'console_scripts', 'legofy')()
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 519, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2630, in load_entry_point
        return ep.load()
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2310, in load
        return self.resolve()
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/pkg_resources/__init__.py", line 2316, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/legofy-0.0.1-py3.2.egg/legofy/cli.py", line 2, in <module>
        import click
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/click/__init__.py", line 18, in <module>
        from .core import Context, BaseCommand, Command, MultiCommand, Group, \
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/click/core.py", line 8, in <module>
        from .types import convert_type, IntRange, BOOL
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/click/types.py", line 7, in <module>
        from .exceptions import BadParameter
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/click/exceptions.py", line 2, in <module>
        from .utils import echo
      File "/home/travis/virtualenv/python3.2.5/lib/python3.2/site-packages/click/utils.py", line 279
        message = message or u''
                               ^
    SyntaxError: invalid syntax

**Comment by mitsuhiko** [comment]
Click does not support Python 3.2.  Upgrade to 3.3 or downgrade to 2.7.

**Comment by niroyb** [comment]
Thanks, just read up on PEP 0414 for which you are the author ;)

Nick
