### ISSUE TITLE
Python 3.4.3 on OS X: _unicodefun: TypeError: 'str' does not support the buffer interface

### ISSUE THREAD

**Issue by ivan** [mitsuhiko/click#494]
I have an OS X / Python 3.4.3 user in https://github.com/ludios/grab-site/issues/64 seeing:

```
Traceback (most recent call last):
  File "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/bin/grab-site", line 4, in <module>
    main.main()
  File "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/lib/python/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/lib/python/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/Volumes/Macintosh HD/Users/user/Library/Python/3.4/lib/python/site-packages/click/_unicodefun.py", line 69, in _verify_python3_env
    if locale.lower().endswith(('.utf-8', '.utf8')):
TypeError: 'str' does not support the buffer interface
```

caused by https://github.com/mitsuhiko/click/blob/8c6c1505adf8ef701f6006a6749a0a493a67fbef/click/_unicodefun.py#L69

I believe the `.strip()` and `.lower()` are operating on bytes instead of unicode, leading to a failure like this:

```
>>> b"ab".strip().lower().endswith(("b", "a"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'str' does not support the buffer interface
```

**Comment by mitsuhiko** [comment]
I'm amazed  this did not come up earlier.

**Comment by johnchristopherjones** [comment]
I encountered this error when setting up a LaunchDaemon to run a script built with click.  This fix merely defers the problem to some other code.  With this changed, the Traceback changes to:

```
Traceback (most recent call last):
  File "/Users/JohnJ/Source/project/myscript.py", line 960, in <module>
    cli()
  File "/Users/JohnJ/Source/project/env3/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/Users/JohnJ/Source/project/env3/lib/python3.5/site-packages/click/core.py", line 675, in main
    _verify_python3_env()
  File "/Users/JohnJ/Source/project/env3/lib/python3.5/site-packages/click/_unicodefun.py", line 119, in _verify_python3_env
    'mitigation steps.' + extra)
RuntimeError: Click will abort further execution because Python 3 was configured to use ASCII as encoding for the environment.  Either run this under Python 2 or consult http://click.pocoo.org/python3/ for mitigation steps.

This system lists a couple of UTF-8 supporting locales that
you can pick from.  The following suitable locales where
discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
```

I'm not sure what the correct fix for this is.  LaunchD is apparently trying to run everything in some ascii-like locale.  Although sub-optimal, this shouldn't be a very peculiar situation.

**Comment by ivan** [comment]
OS X doesn't set up the locale properly anywhere; it's not just a launchd problem.  Terminal emulators are responsible for setting up a UTF-8 locale.  Both Terminal.app and iTerm2 have a setting for it.  It's a very strange situation.  If anything, it's an OS X bug for not setting up the locale, or a Python 3 bug for believing OS X about the ASCII locale.
