### ISSUE TITLE
call module with click decorator fails 

### ISSUE THREAD

**Issue by trigremm** [mitsuhiko/click#526]
fails to me to run imported function with click decorator 

run and error code 
```
python example2.py 
Traceback (most recent call last):
  File "example2.py", line 3, in <module>
    hello(3,'morgan')
  File "/usr/lib/python2.6/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/click/core.py", line 682, in main
    args = list(args)
TypeError: 'int' object is not iterable
```

examlpe1.py code  from http://click.pocoo.org/5/ 

```
import click

@click.command()
@click.option('--count', default=1, help='Number of greetings.')
@click.option('--name', prompt='Your name',
              help='The person to greet.')
def hello(count, name):
    """Simple program that greets NAME for a total of COUNT times."""
    for x in range(count):
        click.echo('Hello %s!' % name)

if __name__ == '__main__':
    hello()
```

example2.py 

```
from example1 import hello
hello(3,'morgan')
```

python and click version 

```
python 
Python 2.6.6 (r266:84292, Nov 22 2013, 12:16:22) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import click 
>>> click.__version__
'6.3'
>>> 
```
same error with python3 

```
python3 
Python 3.5.0 (default, Oct 30 2015, 16:59:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import click 
>>> click.__version__
'6.3'
>>> 
```

**Comment by untitaker** [comment]
`click.command` wraps the function with an object that has a different call signature. `hello(3, 'morgan')` is not valid.
